import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header/Header";
import VerticalLayout from "./layout/VerticalHeader/VerticalLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AZMİU jurnal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header/> */}
        <div className="flex">
          <div className="w-[15%]">
            <VerticalLayout />
          </div>
          <div className="w-[85%]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
